version: "2"
services:
  pg:
    container_name: postgres-resource
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - shipping-network
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
  pgadmin:
      container_name: pgadmin-resource
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
        PGADMIN_DEFAULT_PASSWORD: password
      volumes:
        - pgadmin:/root/.pgadmin
      ports:
        - "5050:80"
      networks:
        - shipping-network
      restart: unless-stopped
networks:
  shipping-network:
    driver: bridge
volumes:
  pg:
  pgadmin: